skip_list:
    - yaml[trailing-spaces]
    - yaml[comments]
    - yaml[new-line-at-end-of-file]
    - yaml[truthy]
    - package-latest
    - fqcn[action-core]

warn-list:
    - yaml[truthy]
    - fqcn[action-core]
